### ISSUE TITLE
getting Internal server error 500, on running login example

### ISSUE THREAD

**Issue by vmnikhil** [bachp/passport-xing#4]
getting Internal server error 500, on running login  example,

InternalOAuthError: Failed to obtain request token
   at Strategy.OAuthStrategy._createOAuthError (C:\Users\MSI0657\Downloads\passport-xing-master\passport-xing-master\examples\login\node_modules\passport-oauth1\lib\strategy.js:396:17)
   at C:\Users\MSI0657\Downloads\passport-xing-master\passport-xing-master\examples\login\node_modules\passport-oauth1\lib\strategy.js:244:41
   at C:\Users\MSI0657\Downloads\passport-xing-master\passport-xing-master\examples\login\node_modules\oauth\lib\oauth.js:543:17
   at passBackControl (C:\Users\MSI0657\Downloads\passport-xing-master\passport-xing-master\examples\login\node_modules\oauth\lib\oauth.js:397:13)
   at IncomingMessage.<anonymous> (C:\Users\MSI0657\Downloads\passport-xing-master\passport-xing-master\examples\login\node_modules\oauth\lib\oauth.js:409:9)
   at emitNone (events.js:91:20)
   at IncomingMessage.emit (events.js:185:7)
   at endReadableNT (_stream_readable.js:974:12)
   at _combinedTickCallback (internal/process/next_tick.js:74:11)
   at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by bachp** [comment]
Do you have this issue over a longer period of time? Could it be that XING is having issues with their servers?

However I haven't tested this since some time. It could be that XING changed their API.

Could you give some more information about what node version you are using?
