### ISSUE TITLE
OAuthStrategy Error

### ISSUE THREAD

**Issue by kmokrzycki** [bachp/passport-xing#5]
Looks like this strategy does not work any more, I am getting below error from example included in repository:

`$ node app.js
App listening on port 3000
Error
    at Strategy.OAuthStrategy._createOAuthError (/Users/user1/Projects/passport-xing/examples/login/node_modules/passport-oauth1/lib/strategy.js:396:17)
    at /Users/user1/Projects/passport-xing/examples/login/node_modules/passport-oauth1/lib/strategy.js:244:41
    at /Users/user1/Projects/passport-xing/examples/login/node_modules/oauth/lib/oauth.js:543:17
    at passBackControl (/Users/user1/Projects/passport-xing/examples/login/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/user1/Projects/passport-xing/examples/login/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

**Comment by bachp** [comment]
I haven't used it in a long time. If you have a patch I would be happy to merge it.
